items:
- name: Ferramentas do Visual Studio para Docker
  href: /dotnet/standard/containerized-lifecycle-architecture/design-develop-containerized-apps/visual-studio-tools-for-docker?toc=/visualstudio/docker/toc.json&bc=/visualstudio/docker/breadcrumb/toc.json
  items:
  - name: 'Início Rápido: Ferramentas do Visual Studio para Docker'
    href: docker-tools.md
  - name: Depuração de aplicativos em um contêiner local do Docker
    href: ../docker/vs-azure-tools-docker-edit-and-refresh.md
  - name: Implantar um contêiner ASP.NET em um registro de contêiner usando o Visual Studio
    href: ../docker/vs-azure-tools-docker-hosting-web-apps-in-docker.md
  - name: Configurar um host do Docker com o VirtualBox
    href: ../docker/vs-azure-tools-docker-setup.md
  - name: Solucionar problemas de desenvolvimento do Visual Studio 2017 com o Docker
    href: ../docker/vs-azure-tools-docker-troubleshooting-docker-errors.md
  expanded: true
ms.openlocfilehash: 0d476d43454bdbba18ce3dba8baffab1108e4250
ms.sourcegitcommit: c0202a77d4dc562cdc55dc2e6223c062281d9749
ms.translationtype: HT
ms.contentlocale: pt-BR
ms.lasthandoff: 01/24/2019
ms.locfileid: "54874700"
